export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const PRODUCTS_GETALL_FAILURE = 'PRODUCTS_GETALL_FAILURE';
      
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const REMOVE_SEARCH_RESULT = 'REMOVE_SEARCH_RESULT';

export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const REMOVE_CART_PRODUCTS = 'REMOVE_CART_PRODUCTS';
export const UPDATE_CART_PRODUCTS = 'UPDATE_CART_PRODUCTS';